---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
  namespace: dante
data:
  application.properties: |
    app.title=KY Container From Configmap 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: init-s2i-tomcat
  namespace: dante
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s2i-tomcat
  template:
    metadata:
      labels:
        app: s2i-tomcat
    spec: 
      containers:
      - name: s2i-tomcat
        image: dante2012/tomcat:8.5-jre8-221
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/tomcat/webapps
        - name: configs
          mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties
          subPath: application.properties
      initContainers:
      - name: init-war
        image: dante2012/s2i-tomcat:init-container
        command: ["sh", "-c", "cp -Rf /app /war/ROOT"]
        volumeMounts:
        - name: workdir
          mountPath: "/war"
      volumes:
      - name: workdir
        emptyDir: {}
      - name: configs
        configMap:
          name: app-configs