---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
  namespace: dante
data:
  application.properties: |
    app.title=KY Container From Configmap 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s2i-tomcat
  namespace: dante
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s2i-tomcat
  template:
    metadata:
      labels:
        app: s2i-tomcat
    spec: 
      containers:
      - name: s2i-tomcat
        image: dante2012/s2i-tomcat:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
        env:
        - name: LOG_HOME
          value: /usr/local/tomcat/logs/s2i
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: logs
          mountPath: /usr/local/tomcat/logs 
        - name: configs
          mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties
          subPath: application.properties
      volumes:
      - name: logs
        hostPath:
          path: /Users/dante/Documents/Project/java-world/hna/caas/caas-tomcat/logs/k8s-data
      - name: configs
        configMap:
          name: app-configs
          items:
          - key: application.properties
            path: application.properties
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - s2i-tomcat
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      
---
apiVersion: v1
kind: Service
metadata: 
  name: s2i-tomcat
  namespace: dante
spec:
  selector:
    app: s2i-tomcat
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s2i-ingress
  namespace: dante
  annotations:
    nginx.org/rewrites: "serviceName=s2i-tomcat rewrite=/"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: s2i-tomcat
          servicePort: 8080