apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s2i-tomcat
  namespace: dante
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s2i-tomcat
  template:
    metadata:
      labels:
        app: s2i-tomcat
    spec: 
      containers:
      - name: s2i-tomcat
        image: xx:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: s2i-tomcat
  namespace: dante
spec:
  selector:
    app: s2i-tomcat
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s2i-ingress
  namespace: dante
  annotations:
    nginx.org/rewrites: "serviceName=s2i-tomcat rewrite=/"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /tom
        backend:
          serviceName: s2i-tomcat
          servicePort: 8080