apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s2i-tomcat
  namespace: dante
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s2i-tomcat
  template:
    metadata:
      labels:
        app: s2i-tomcat
    spec: 
      containers:
      - name: s2i-tomcat
        image: s2i-tomcat:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
        volumeMounts:
        - name: logs
          mountPath: /usr/local/tomcat/logs 
      volumes:
      - name: logs
        hostPath:
          path: /Users/dante/Documents/Project/spring/hna/caas/caas-tomcat/logs/k8s-data
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - s2i-tomcat
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata: 
  name: s2i-tomcat
  namespace: dante
spec:
  selector:
    app: s2i-tomcat
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s2i-ingress
  namespace: dante
  annotations:
    nginx.org/rewrites: "serviceName=s2i-tomcat rewrite=/"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: s2i-tomcat
          servicePort: 8080