apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label.s2i }}
spec: 
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: {{ .Values.nodePort.s2i }}
  selector:
    deployment: {{ .Values.label.s2i }}