apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label.zk }}
spec: 
  type: NodePort
  ports:
    - name: client
      port: 2181
      targetPort: 2181
      protocol: TCP
      nodePort: {{ .Values.nodePort.zk }}
  selector:
    statefulSet: {{ .Values.label.zk }}